### ISSUE TITLE
Ensure that XML that is sent to OJS3 is being associated with Lens Viewer

### ISSUE THREAD

**Issue by axfelix** [kaschioudi/ojs3-markup#1]
I'm not sure that the XML returned by the service currently is being directly associated with Lens Viewer to open it -- @asmecher, what needs to be done to ensure that happens?

**Comment by asmecher** [comment]
Currently, the Lens plugin just needs to be enabled, and the MIME type of the galley file needs to be `application/xml`.

**Comment by axfelix** [comment]
Got it. Are we enabling Lens out of the box? Why not if not?

**Comment by asmecher** [comment]
Yes, for new installs.

**Comment by axfelix** [comment]
OK, perfect. Closing this, thanks!

**Comment by axfelix** [comment]
Actually -- can we catch text/xml too? I seem to remember hitting that on some servers in the past without much/any reason for why it would be different from application/xml.

**Comment by asmecher** [comment]
Added `text/xml`.
