### ISSUE TITLE
Plugin settings menu does not register itself consistently

### ISSUE THREAD

**Issue by axfelix** [kaschioudi/ojs3-markup#11]
On a beater OJS3 instance in which I've tried installing and removing the plugin a few times, I can't always get the new plugin settings menu to appear on the top bar.

**Comment by axfelix** [comment]
Also, I seem to be having trouble with some DB tables not being generated correctly on some instances:

`[Thu Feb 02 10:07:47.228025 2017] [:error] [pid 6958] [client 71.7.135.56:50737] ojs2: DB Error: Table 'ojs-plugin-qa.markup_jobinfos' doesn't exist, referer: http://lib-garnett.lib.sfu.ca/ojs-plugin-qa/index.php/testing/workflow/index/2/3[Thu Feb 02 10:09:09.101306 2017] [:error] [pid 6958] [client 69.172.157.238:51249] ojs2: DB Error: Table 'ojs-plugin-qa.markup_jobinfos' doesn't exist, referer: http://lib-garnett.lib.sfu.ca/ojs-plugin-qa/index.php/testing/workflow/index/2/3`
`[Thu Feb 02 10:09:26.498498 2017] [:error] [pid 7088] [client 69.172.157.238:51259] PHP Warning:  include(/var/www/html/ojs-plugin-qa/cache/fc-pluginSettings-1-webfeedblockplugin.php): failed to open stream: No such file or directory in /var/www/html/ojs-plugin-qa/lib/pkp/classes/cache/FileCache.inc.php on line 46, referer: http://lib-garnett.lib.sfu.ca/ojs-plugin-qa/index.php/testing/workflow/index/2/3`

It's possible I actually don't know how to install plugins properly in OJS3?

**Comment by jmacgreg** [comment]
How did you install the plugin?

**Comment by axfelix** [comment]
Cloning it into the plugins directory before running the OJS installer on a new instance

**Comment by jmacgreg** [comment]
That should do it. I just tried dis/re-enabling it on the plugins page, that may make a difference. Do those tables exist now? Is there a schema in the plugin to create them?

**Comment by axfelix** [comment]
https://github.com/kaschioudi/ojs3-markup/blob/master/schema.xml

Still not generated on this server, though.

**Comment by jmacgreg** [comment]
Yep, a few local attempts at installing results in that table not being present. 

installation steps: 
`git clone https://github.com/kaschioudi/ojs3-markup plugins/generic/markup`
`php tools/upgrade.php upgrade // to install the plugin`
I then enabled the plugin via the GUI. I have access to the "OTS Settings" tab, but the table `markup_jobinfos` is not in my database.

**Comment by kaschioudi** [comment]
I believe schema.xml gets executed only on plugin installation or system installation with the plugin in the right directory. Otherwise you need to run the following command: `php tools/dbXMLtoSQL.php -schema execute path/to/schema.xml`

**Comment by asmecher** [comment]
The plugin needs to implement `getInstallSchemaFile` -- see https://github.com/pkp/staticPages/blob/master/StaticPagesPlugin.inc.php#L191 for example. That'll cause it to create the tables on install/upgrade.

**Comment by axfelix** [comment]
Thanks, @asmecher !

Should be handled by https://github.com/kaschioudi/ojs3-markup/pull/12.
