### ISSUE TITLE
Unable to fetch citation styles

### ISSUE THREAD

**Issue by jmacgreg** [kaschioudi/ojs3-markup#15]
After installing the plugin locally, I can get to the OTS Settings tab, but get a popup warning "Unable to fetch citation styles". The citation styles dropdown is subsequently unpopulated, and given that it's a required selection to save the page settings, I can't save. 

I am not sure if this is a problem with trying to run the application on my local laptop rather than an actual web server or not. @axfelix, we ran into this earlier, I believe. I'm running a fresh checkout of the plugin in master, and a fresh OJS ojs-stable-3_0_2 instance.

**Comment by jmacgreg** [comment]
NB: PHP curl support has been enabled.

**Comment by axfelix** [comment]
Somebody else reported this and I haven't been able to duplicate. I'll try again tomorrow.

**Comment by axfelix** [comment]
I think that's done in js so it would be in the browser console rather than the apache logs... any chance you're seeing something illuminating?

**Comment by kaschioudi** [comment]
I just tried and I can't reproduce on my macbook. 

What's your local stack (Wamp, Mamp, easyphp, etc)?

**Comment by jmacgreg** [comment]
Argh - this was due to Privacy Badger blocking external content. Apologies for the time waster!
