### ISSUE TITLE
Consider removing OTS demo server link info

### ISSUE THREAD

**Issue by jmacgreg** [kaschioudi/ojs3-markup#16]
The OTS settings page currently includes a link to the demo server (http://xml-demo.lib.sfu.ca/) in the following text: 

> You can register for our demonstration OTS instance [here]

... and it also auto-populates the Open Typesetting Stack URL parameter with the same URL. That URL doesn't appear to actually work/be active. 

I'd suggest removing the above sentence entirely, as well as the auto-suggestion. The plugin can work with any OTS stack out there, and I think we can simply provide some info regarding the demo service in our release notes/documentation, and otherwise leave this blank.

**Comment by jmacgreg** [comment]
I'll have some generally overhauled text for this shortly.

**Comment by kaschioudi** [comment]
the link to OTS demo server is http://pkp-xml-demo.lib.sfu.ca/
