### ISSUE TITLE
"Review" checkbox item text on settings page is broken

### ISSUE THREAD

**Issue by jmacgreg** [kaschioudi/ojs3-markup#17]
Fix coming shortly.

**Comment by kaschioudi** [comment]
Hi @jmacgreg ,

Witht his fix, we will end up with "manager.publication.reviewStage" twice. 

If I remember correctly, Alec told me that "workflow.review.internalReview" is actually used by OMP only. Should we just remove that stage?

**Comment by jmacgreg** [comment]
Ah, good catch - I didn't see the other review stage. And yep, for the OJS plugin just go with external review.

**Comment by kaschioudi** [comment]
cf: https://github.com/kaschioudi/ojs3-markup/issues/9
