### ISSUE TITLE
PDF conversion to XML is not working.

### ISSUE THREAD

**Issue by pilasou** [kaschioudi/ojs3-markup#20]
I am unable to convert a PDF file in XML using the OJS/OTS plugin (with an MS Word file, everything went well, I get an XML and can open it in Texture). 

The PDF consist of a few text pages with figures and tables. It is converted from Word (see PDF attached).
[Sed congue, ipsum nec pellentesque laoreet.pdf](https://github.com/kaschioudi/ojs3-markup/files/822302/Sed.congue.ipsum.nec.pellentesque.laoreet.pdf)
 
I end up with a Failed message (see file attached) with no way of knowing what happenned.
![pdf_convertion_failed](https://cloud.githubusercontent.com/assets/19291880/23626610/7e244c14-027b-11e7-8dc5-b8c5dd50c8b4.png).

Here is what I do:  
Make a new submission, use a PDF file
In the Submission tab I clic on Convert to XML below the file name.
Then, clic on Trigger Job
The Job launch, gets Pending, and then Fail after a few time.

Thanks.
pierre

**Comment by kaschioudi** [comment]
Hi @pilasou! the failure is not related to this plugin. I tried to convert the file directly on OTS and it also fails. The failure happens at XMP stage. It looks like the system is unable to parse metadata from xml document. 

@axfelix any hint?

**Comment by axfelix** [comment]
Failing at the XMP stage is pretty unusual, since that's merging our extracted metadata with our generated PDF -- i.e., nothing too exotic by that point, and nothing we don't have control over. I suspect that exiftool is choking on special characters in the metadata extracted from the document...

Thanks for reporting this failure case, @pilasou! I think we'll probably just have to sanitize what we pass to exiftool.

**Comment by axfelix** [comment]
@kaschioudi the metadata.json that gets created when the OJS plugin makes a submission to OTS with known-good metadata as an additional POST parameter should be 100% UTF8-friendly, right?

[metadata.json.txt](https://github.com/kaschioudi/ojs3-markup/files/823037/metadata.json.txt)
[document_from_pdf.xml.txt](https://github.com/kaschioudi/ojs3-markup/files/823036/document_from_pdf.xml.txt)
[document.xml.txt](https://github.com/kaschioudi/ojs3-markup/files/823038/document.xml.txt)

**Comment by axfelix** [comment]
Looking into this further -- it seems like our option to merge in known-good metadata from OJS as an additional parameter posted to the OTS API had a bug with PDF input (we might've only tested it with Word). We'll be moving the known-good metadata merge out of the existing "Merge" module to fix this.

**Comment by pilasou** [comment]
I have made further test and the XML file is generated wihtout failling now. However, when converting a PDF, it always skip the <journal-meta/> element. When converted from Word or ODT, this tag contains the journal title and publisher. See example (converted from a PDF file generated by LaTeX): 
[8-99Z_Article Text-28-1-2-20170308_LateX_simple.xml.txt](https://github.com/kaschioudi/ojs3-markup/files/829099/8-99Z_Article.Text-28-1-2-20170308_LateX_simple.xml.txt)

**Comment by pilasou** [comment]
This bug may be linked to this issue: when the Galley files are generated from a PDF, the EPUB galley is empty. Other Galleys are generated (PDF and XML).
Exemple of EPUB: [7-99Z_Article Text-72-1-10-20170309.epub.txt](https://github.com/kaschioudi/ojs3-markup/files/832105/7-99Z_Article.Text-72-1-10-20170309.epub.txt)

**Comment by axfelix** [comment]
Hi @pilasou -- this should all be fixed in the current release if you want to test.
