### ISSUE TITLE
The "Insert" button in the top bar only offer a "Cross reference" option.

### ISSUE THREAD

**Issue by pilasou** [kaschioudi/ojs3-markup#21]
The insert button was introduced as a feature to add a JATS element that is not yet implemented in the WYSIWYG Texture. However, it only offer a Cross reference option (see image attached
![texture_insert](https://cloud.githubusercontent.com/assets/19291880/23628250/be6c77aa-0281-11e7-9589-7f561bd58019.PNG)
).
Thanks.
pierre

**Comment by axfelix** [comment]
Fixed in newest Texture editor included with plugin.
