### ISSUE TITLE
Add "backlog convert" option for journals wanting to push all old articles to XML

### ISSUE THREAD

**Issue by axfelix** [kaschioudi/ojs3-markup#25]
I think the best place for this is *probably* in plugin settings, which is somewhat non-obvious but I don't know if there's a better option.

We need a one-click option for journals wanting to convert a lot of their old content to XML, as well as a non-brittle process that can:

- run in the background
- not failover between submissions for any reason
- decide where to pull the content for batch conversion from by default (this can either be our choice, e.g., we add some logic to use the PDF galley if present, and fall back to other versions if not, or we can add a chooser for journals to pick on their own)

**Comment by axfelix** [comment]
Batch conversion using this method will likely *not* be perfect as it will bypass the Texture editing workflow and just dump out the first-pass result from OTS, but we should have it to support https://github.com/kaschioudi/ojs3-markup/issues/26

**Comment by asmecher** [comment]
@kaschioudi, I'll be talking with Erudit on the 15th and would like to give a progress update -- how is this coming along?

**Comment by axfelix** [comment]
I saw a demo of this last week and it was almost fully working, @kaschioudi is just doing a refactor before merging. We should be able to present a demo next week of at least the batch conversion, not sure if you were hoping to have the feed implemented by then too.

**Comment by kaschioudi** [comment]
I just created a PR for #25, #26 and #27. 

cf: https://github.com/kaschioudi/ojs3-markup/pull/36

Here's the commit for this issue: https://github.com/kaschioudi/ojs3-markup/commit/d0a481922f0cc959f7ecad6a423cf1d990bc751e

**Comment by kaschioudi** [comment]
@axfelix @asmecher 
Please see https://github.com/kaschioudi/ojs3-markup/commit/cfac0bdf428a53d6905140209940aaaf4f34a5f3 for the changes we discussed.

**Comment by axfelix** [comment]
Thanks, @kaschioudi !

@asmecher , since you had more specific ideas of what you wanted to see than I expected the last time we met, did you want to see if you could get this running on your own at this point as a sanity check before we meet again? I'll test anyway, but that might be easier.

**Comment by asmecher** [comment]
@axfelix and @kaschioudi, sure, I'll run through it.

**Comment by asmecher** [comment]
Feedback posted over on https://github.com/kaschioudi/ojs3-markup/pull/36.
