### ISSUE TITLE
Always populate "Layout version" with XML when returning galleys from OTS

### ISSUE THREAD

**Issue by axfelix** [kaschioudi/ojs3-markup#26]
It'd be great if we could use this plugin as a means of re-adding an OAI endpoint to OJS3 -- it can serve our XML directly. To do this, we need the plugin to always return XML to one predictable place, only it can't be galleys, because galleys are *always* published, and some journals might not want to publish XML (which is why we have the toggle in plugin settings) yet still enable the OAI endpoint.

**Comment by axfelix** [comment]
I can take a crack at this one first.

**Comment by axfelix** [comment]
Should go in https://github.com/kaschioudi/ojs3-markup/blob/master/MarkupGatewayPlugin.inc.php#L375, I assume...

**Comment by axfelix** [comment]
Note, this is called "production ready files" rather than "layout version" in OJS 3 (still had the 2.x name in my head) -- not sure what the best way to manipulate documents in this stage is though.

**Comment by asmecher** [comment]
@kaschioudi, let me know when you've got something I can test with -- I'll be writing the code to pick up from here and present the XML content via OAI.

**Comment by kaschioudi** [comment]
@asmecher 

I just created a PR for #25, #26 and #27. 

cf: https://github.com/kaschioudi/ojs3-markup/pull/36

In case you would like to cherry pick, here's the commit for this issue: https://github.com/kaschioudi/ojs3-markup/commit/5e3935f6befb48ac1dab58130becfa0be290b716
