### ISSUE TITLE
Update to Texture Alpha 3

### ISSUE THREAD

**Issue by axfelix** [kaschioudi/ojs3-markup#27]
There's been a new release of Texture and we need to update this plugin to work with it. It should be a nearly drop-in replacement, but I wanted to clarify some things:

- it's no longer packaged as three directories containing css/fonts/js -- did we do that?
- does this template (https://github.com/kaschioudi/ojs3-markup/blob/master/templates/editor.tpl) deliberately declare *all* the js and css files packed in with Texture? that seems like a weird choice even if it's not all that difficult to maintain...
- I *think* the only other thing we'd need to change if the method of passing documents to Texture is still the same (which I believe it is) is this declaration here: https://github.com/kaschioudi/ojs3-markup/blob/cef61ddfebd01c67f0ae179b1200945721fb33e7/MarkupPlugin.inc.php#L183, but I'm also not clear on how it's used (why do we need to declare all of the js files individually and then have a variable for the directory path itself)?

This *should* be relatively straightforward and I'm hoping it can be a high priority.

**Comment by axfelix** [comment]
Going to proceed under the assumption that passing documents to Texture indeed has not changed, due to this function being present in both the new and the currently-shipping builds...

      _loadDocument() {
        const configurator = this.getConfigurator();
        this.props.readXML(this.props.documentId, function(err, xmlStr) {

**Comment by axfelix** [comment]
Just changing the css and js declarations and dropipng in the new version is producing:

    Uncaught TypeError: Cannot read property 'XMLSchema' of undefined
        at JATSArchiving.js:4
        at JATSArchivingData.start (texture.js:4)
        at texture.js:5

grepping in the pacakge for JATSArchiving.js is producing some weird results. @michael @oliver---- any immediate ideas? We can probably return to this when @kaschioudi has time as he understands the OJS implementation much better than I do, but just curious if there's something obvious...

**Comment by obuchtala** [comment]
Ah, I suppose, the bundle is not fully self-contained anymore. I think in this case it is missing the substance bundle. I'll be right back with more details...

**Comment by axfelix** [comment]
Thanks, take your time, I know it's late there :)

**Comment by obuchtala** [comment]
![image](https://user-images.githubusercontent.com/284099/28548709-d4c6d8fc-70d5-11e7-9a7c-592d47eec2ff.png)

Could you try to do something similar. I.e. load the bundled substance.js before texture.js?

**Comment by obuchtala** [comment]
> snippet taken from editor.html as in the released zip

**Comment by axfelix** [comment]
That's an improvement -- still whitescreening, but now throwing `Token abstract already used. Ignoring this transition.`

**Comment by obuchtala** [comment]
That should be ok... if white screening... then we have something else... hmmm

**Comment by obuchtala** [comment]
If not more errors are shown, I am a bit lost. Maybe we should create a bundle with some more logging?

**Comment by axfelix** [comment]
If that's easy for you to do quickly, that'd be appreciated -- I'm not sure when @kaschioudi will have time to look into this.

**Comment by obuchtala** [comment]
Would it work for you, if I created a branch where you build it and use the dist?

**Comment by axfelix** [comment]
I don't think I'd know the best places to add more logging statements in that case...

**Comment by obuchtala** [comment]
I was more thinking about me to add logging, and you `npm run bundle`

**Comment by axfelix** [comment]
oh, sure!

**Comment by obuchtala** [comment]
cool. Gimme some minutes...

**Comment by obuchtala** [comment]
Sooo.... you could do in a clone of the texture repo:
```
git fetch origin
git checkout  alpha-3-integration
npm install
npm run bundle
```

also try 
```
npm start
```
first, if everything is working locally.

**Comment by obuchtala** [comment]
You find the bundle in `dist`

**Comment by axfelix** [comment]
Still whitescreening with the same Token abstract already used error (it also threw this when building with npm)

**Comment by michael** [comment]
What JATS file is used? Can you send me a zip with your full integration setup?

(the Token abstract already used error is not critical)

**Comment by axfelix** [comment]
I've tried both of these, I can try to package the OJS instance in an intelligent way a little later...



[jats.zip](https://github.com/kaschioudi/ojs3-markup/files/1177376/jats.zip)

**Comment by michael** [comment]
The first file does not pass through the validator. It should shows an error like this:

![image](https://user-images.githubusercontent.com/2931/28668419-f06e1c2c-72cf-11e7-8896-b8c51fc71eb3.png)

- fpage and lpage must not be empty if present

2nd file errors in Texture's figure rendering code - I'm investigating.

**Comment by michael** [comment]
OK second file has wrong markup of `<fig>` element.

```xml
<fig position="float" orientation="portrait">
  <graphic xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="media/image1.png" id="IDf9970209-5376-452b-97e9-f4506211bc00" position="float" orientation="portrait" xlink:type="simple">
    <label>Figure 1</label>
    <caption>
      <p>Brain wave samples with dominant frequencies belonging to beta, alpha, theta, and delta band</p>
    </caption>
  </graphic>
</fig>
```

Caption should go not be in graphic - We should make validator fail in such a case (creating an issue).

Apart from that Texture UI expects the figure to have a title (`caption > title`) that's why it is whitescreening. Will be fixed in next release.

To help us track down errors like those please open the developer console in chrome and enable "pause on exception". Then you can include a screenshot of the stacktrace, which we can then investigate.

**Comment by michael** [comment]
@axfelix can we include these two files in the repo?

**Comment by axfelix** [comment]
Oh, sure! Sorry, I would've actually tried to validate those against the DTD first, but I thought I'd already tested both of those "sets" of documents against Texture earlier on (one is our professionally marked up set, one is regular stack output) and we had all import errors resolved. Thanks for this!

**Comment by axfelix** [comment]
PS, the validator is requiring that volume and fpage be _present_ *and* not empty, which isn't a requirement that all of our content can fulfill:

    /article/front: [error]article-meta checking: Either <fpage> or <elocation-id> must be present in <article-meta> (Tagging Guidelines)

    /article/front/article-meta: [error]empty element check: volume should not be empty

**Comment by axfelix** [comment]
What's the best thing for me to capture from pause-on-exception errors? I'm still hitting whitescreens for the majority of our output and our corpus for now...

**Comment by michael** [comment]
Regarding `fpage` and `volume`... Is that really the case? I think it only errors if it is present but without text (that's enforced by JATS itself). If `volume` or `fpage` is not present that should be fine?

Regarding errors, just post a screenshot of the callstack like so: 

![image](https://user-images.githubusercontent.com/2931/28736441-18453b02-73ea-11e7-8004-a796b59fee16.png)

For each unique error you see it would be good to have a separate issue in Texture, showing the stacktrace and having the corresponding XML file attached (ideally one that we can include in the Texture build, so we can work towards a set of examples to power an integration testsuite)

How should we proceed generally? I'd favor collecting a few more issues and then doing one bigger iteration fixing them in one go and provide you an updated build. Of course if some error is really blocking i will try to provide a hotfix. Please put the "priority" label on issues that are critical.

**Comment by axfelix** [comment]
OK, will do -- I need to get it whitescreening a little less by EOD Monday, if possible. Will add some new issues.

**Comment by axfelix** [comment]
![image](https://user-images.githubusercontent.com/252047/28737037-9b06d670-73a1-11e7-9bb7-128290b4aa0c.png)

this doesn't look useful to me...

**Comment by obuchtala** [comment]
Yeah, these errors you need to skip. jquery throws exceptions instead of proper try-catch and if then else.

Edit: they use it to detect browser features.

**Comment by axfelix** [comment]
Go on...

**Comment by axfelix** [comment]
Oh hang  on, you mean just step through? OK, wait a sec...

**Comment by obuchtala** [comment]
exactly ;)

**Comment by axfelix** [comment]
![image](https://user-images.githubusercontent.com/252047/28737183-2976364e-73a2-11e7-8fa2-8d918a55c16c.png)

?

**Comment by obuchtala** [comment]
$rdf is not defined ;)

**Comment by obuchtala** [comment]
another jquery one

**Comment by obuchtala** [comment]
`> next`

**Comment by axfelix** [comment]
OK, whereas this is an actual error with our output, I think:

![image](https://user-images.githubusercontent.com/252047/28737220-511ed476-73a2-11e7-8677-8b0f97a317a7.png)

meTypeset will sometimes leave Zotero cues behind if it can't resolve a reference...

**Comment by obuchtala** [comment]
Zotero is not defined

**Comment by axfelix** [comment]
It's actually getting to the point of trying to invoke some Zotero code, though, which seems like something Texture wouldn't be doing if we *just* had lingering Zotero metadata in the doc?

![image](https://user-images.githubusercontent.com/252047/28737261-8665066e-73a2-11e7-9844-c4a8e993b5b8.png)

**Comment by obuchtala** [comment]
Ok, can u explain in more detail?

**Comment by axfelix** [comment]
Actually, there's no lingering Zotero metadata in that doc at all, it seems whatever threw that issue is purely on the Substance side (although probably an issue with the doc, of course).

Want me to just upload it, or keep stepping through?

**Comment by obuchtala** [comment]
We don't have any Zotero support in Substance. Let's step through until we reach something in our land.

**Comment by axfelix** [comment]
OK, weird -- I assume you'd just pulled some Zotero code in as part of your citation stuff, I have no idea where that's actually coming from in that case...

**Comment by axfelix** [comment]
Oh that's just my chrome extension, dammit. Ha, hang on.

**Comment by obuchtala** [comment]
Aha ;)

**Comment by axfelix** [comment]
Now this is the only non-jquery error I'm hitting:

![image](https://user-images.githubusercontent.com/252047/28737482-95a15d16-73a3-11e7-87a9-7ce5cc416c7f.png)

**Comment by obuchtala** [comment]
Oi. Still not my land ;)

**Comment by obuchtala** [comment]
Let's continue with a zip. We need to enable our validator UI. Somehow, this does not get shown on your side.

**Comment by axfelix** [comment]
Well, then I really have no idea what's causing this one to die ...
[4-99Z_Article Text-5-1-2-20170728.zip](https://github.com/kaschioudi/ojs3-markup/files/1184340/4-99Z_Article.Text-5-1-2-20170728.zip)

**Comment by obuchtala** [comment]
I will take a look. Gimme some minutes.

**Comment by obuchtala** [comment]
Ok. The integration code is not robust against non-parsable XML. In earlier versions, the import dialog showed up, but now it is crashing. @michael could you help fixing this? I.e. JATSImporter is implemented to check the validity of the XML and show an error. The current boot script parses the XML, but is not robust against errors here.

**Comment by axfelix** [comment]
I get this output from xmllint -- obviously not perfect but should be parseable:

$ xmllint --valid 4-99Z_Article\ Text-5-1-2-20170728.xml > ~/Desktop/text.txt
4-99Z_Article Text-5-1-2-20170728.xml:20: element name-alternatives: validity error : No declaration for element name-alternatives
hor"><name-alternatives><string-name>otsalpha </string-name></name-alternatives>

                                                                               ^

4-99Z_Article Text-5-1-2-20170728.xml:20: element contrib: validity error : Element contrib content does not follow the DTD, expecting ((anonymous | collab | name)* , degrees* , (address | aff | author-comment | bio | email | ext-link | on-behalf-of | role | uri | xref)*), got (name-alternatives email)
lpha </string-name></name-alternatives><email>axfelix@gmail.com</email></contrib

                                                                               ^

4-99Z_Article Text-5-1-2-20170728.xml:68: element ext-link: validity error : Element xref is not declared in ext-link list of possible children
ade22-d16e-4f5c-8a12-3c3b1e3e8d38" ref-type="table">Table 1</xref>." </ext-link>

                                                                               ^

4-99Z_Article Text-5-1-2-20170728.xml:74: element ext-link: validity error : Element xref is not declared in ext-link list of possible children
7170c-04e9-45a1-99b8-f4f6cd2f9602" ref-type="table">Table 2</xref>." </ext-link>

                                                                               ^

4-99Z_Article Text-5-1-2-20170728.xml:95: element ext-link: validity error : Element xref is not declared in ext-link list of possible children
a4827-b38b-4bc7-8dd0-7e7167217009" ref-type="table">Table 3</xref>." </ext-link>

                                                                               ^

4-99Z_Article Text-5-1-2-20170728.xml:104: element ext-link: validity error : Element xref is not declared in ext-link list of possible children
b16f5-ed99-4db7-935a-351772124f8b" ref-type="table">Table 4</xref>." </ext-link>

                                                                               ^

4-99Z_Article Text-5-1-2-20170728.xml:109: element ext-link: validity error : Element xref is not declared in ext-link list of possible children
d895a-de51-442e-ae80-c4daa62f6cda" ref-type="table">Table 5</xref>." </ext-link>

                                                                               ^

4-99Z_Article Text-5-1-2-20170728.xml:116: element ext-link: validity error : Element xref is not declared in ext-link list of possible children
d7b38-ce7c-428d-8e94-7ed88892861e" ref-type="table">Table 6</xref>." </ext-link>

                                                                               ^

4-99Z_Article%20Text-5-1-2-20170728.xml:295: element xref: validity error : IDREFS attribute rid references an unknown ID "ID375c02a1-6c96-44b3-b70c-fa873f790002"
4-99Z_Article%20Text-5-1-2-20170728.xml:33: element xref: validity error : IDREFS attribute rid references an unknown ID "TO_LINK"
4-99Z_Article%20Text-5-1-2-20170728.xml:33: element xref: validity error : IDREFS attribute rid references an unknown ID "TO_LINK"
4-99Z_Article%20Text-5-1-2-20170728.xml:522: element xref: validity error : IDREFS attribute rid references an unknown ID "TO_LINK"

**Comment by obuchtala** [comment]
![image](https://user-images.githubusercontent.com/284099/28737969-405c5466-73f1-11e7-9402-158949a30acb.png)

**Comment by obuchtala** [comment]
There seems to be some illegal white-space at the beginning of the XML.

**Comment by obuchtala** [comment]
Just for clarification, we use DOMParser from the browser. It does seem to choke with white-space at the beginning. Dunno if that is valid XML or not. But it is a problem in the browser.
We could add trimming to our implementation before calling DOMParser, if this is a recurring problem, though.

**Comment by axfelix** [comment]
It might be -- I could add sanitization on our end, but I'm not sure what I need to sanitize yet, and since xmllint doesn't seem to have a problem with the document, I'm not sure where to start.

**Comment by axfelix** [comment]
[3-99Z_Article Text-4-1-2-20170727.zip](https://github.com/kaschioudi/ojs3-markup/files/1184377/3-99Z_Article.Text-4-1-2-20170727.zip)

This doc is also only throwing the same requireNative issue...

**Comment by obuchtala** [comment]
Same thing.

**Comment by axfelix** [comment]
OK, should probably try to find out where this illegal whitespace is coming from. Any ideas? Other than just passing it through a trim function and hoping that works?

**Comment by obuchtala** [comment]
Nah, sorry. In that case it was `<journal-id>` and `<year>` being incomplete.

**Comment by obuchtala** [comment]
You don't see the import dialog? we need to fix this!

**Comment by axfelix** [comment]
We need to fix that *and* get better at allowing empty metadata values :)

**Comment by obuchtala** [comment]
I think it is JATS which needs to be fixed then ;)

**Comment by obuchtala** [comment]
https://jats.nlm.nih.gov/archiving/tag-library/1.1/element/year.html

**Comment by obuchtala** [comment]
![image](https://user-images.githubusercontent.com/284099/28738271-c9b934f8-73f2-11e7-977f-6cff981f3ebc.png)

**Comment by axfelix** [comment]
I'm fairly sure most of the empty values we're creating right now were because earlier tools were even more upset when they didn't exist at all, even if they're required to be filled, but I'll double check that.

**Comment by obuchtala** [comment]
I mean, maybe we misinterpret `(#PCDATA)` and `(#PCDATA)?` which both exist in the schema.
Then we need to make it more lax.

**Comment by obuchtala** [comment]
We see the errors, because we take the schema seriously ;)

**Comment by axfelix** [comment]
:) I know! It's good that you do!

That doc is still whitescreening for me after removing journal-id and year, though...

**Comment by obuchtala** [comment]
We need to fix the former issue. But for now send me your updated XML.

**Comment by axfelix** [comment]
[3-99Z_Article Text-4-1-2-20170727.zip](https://github.com/kaschioudi/ojs3-markup/files/1184390/3-99Z_Article.Text-4-1-2-20170727.zip)

**Comment by obuchtala** [comment]
BTW, what I do:
I have a vanilla texture clone. Then I copy and paste XML replacing one of the samples and open it via the landing page served when running `npm start`

**Comment by obuchtala** [comment]
It is working for me.

**Comment by axfelix** [comment]
Got it, thanks. I've been testing inside of OJS hoping we I can get at least one doc to work that way but I think I need to just run texture standalone to isolate these, I guess

**Comment by axfelix** [comment]
OK, that's interesting -- so there may _still_ be something wrong in our integration at this point?

**Comment by obuchtala** [comment]
Seems so.

**Comment by axfelix** [comment]
Good to know! I think that's enough to convince me to just focus on standalone Texture demos during our workshop next week! But the good news is there's still plenty of UX hands-on stuff to be done there.

**Comment by axfelix** [comment]
@kaschioudi  -- we'll have to revisit integration issues when you have time.

**Comment by obuchtala** [comment]
Let's get our validator page shown on your side. Or at least in a dev setup. That's why we have introduced it in first place :)

**Comment by obuchtala** [comment]
Or maybe the code does not even get to that point.. for whatever reason.

**Comment by axfelix** [comment]
I'm sure that's just an issue with our integration, now; let me check if I can get it thrown when running standalone.

**Comment by axfelix** [comment]
Yeah, it's working fine standalone. OK, well, unless you have any suggestions about what might be going wrong with the integration, we might have to leave it for now...

**Comment by obuchtala** [comment]
Do we have an integration to test by ourselves somewhere?

**Comment by axfelix** [comment]
Ah, certainly, if you're willing!

http://lib-garnett.lib.sfu.ca/ojs-plugin-alpha-12/index.php/test/submissions

with username: "otsalpha" and password "t3sting"

click through on any of the submissions, then expand the context menu below any of the XML documents, and try "Edit with Texture".

**Comment by axfelix** [comment]
Also you can obviously bill for this :)

**Comment by obuchtala** [comment]
On the first glance, I don't see any boot script. Maybe this has changed (@michael?)
I only see script tags including substance.js and texture.js which are just the libraries.
There should be some code doing something like:
```
<script type="text/javascript">
      const { Texture } = window.texture
      window.onload = function() {
        window.app = Texture.mount({
          documentId: ... documentID maybe from HTML params ... or somehow...,
          readXML: function(documentId, cb) {
             // HERE: retrieve the actual XML string
            xmlStr = ... some ajax request or something
            cb(null, xmlStr)
          },
          writeXML: function(documentId, xml, cb) {
            // HERE: store the XML string into backend somehow
            cb(null)
          }
        }, document.body)
      }
    </script>
```

**Comment by obuchtala** [comment]
I think @michael needs to assist here.

**Comment by axfelix** [comment]
And he's not available at midnight on a Friday?!

**Comment by obuchtala** [comment]
Haha. Yeah. That sucks.

**Comment by axfelix** [comment]
:) ok, thanks for all your help so far.

**Comment by obuchtala** [comment]
I will be available the next two days. Should there be something I can help with, I will be there.

**Comment by obuchtala** [comment]
BTW, I spotted a `<script>` tag loading a `vfs`. This is what we do in the example, in the lack of a real backend. Probably you don't want to do it that way, but just use ajax. cc @kaschioudi

**Comment by michael** [comment]
Hey! 

As Oliver said, in your integration the boot-script is missing. This  is also where you configure where to read the files from. So in a new script tag in the head do this:

**Comment by michael** [comment]
Sorry, previous comment submitted too early accidentally. So do this:

```js
window.onload = function() {
  window.app = Texture.mount({
    documentId: file,
    readXML: function(documentId, cb) {
      // read XML via Ajax from OJS
      let xmlStr = ...
      cb(null, xmlStr)
    },
    writeXML: function(documentId, xml, cb) {
      // write xml string to OJS
    }
  }, document.body)
}
```

You can remove the vfs.js script.

**Comment by kaschioudi** [comment]
> does this template (https://github.com/kaschioudi/ojs3-markup/blob/master/templates/editor.tpl) deliberately declare all the js and css files packed in with Texture? that seems like a weird choice even if it's not all that difficult to maintain...

@axfelix This is based on `editor.html` from texture example (see https://github.com/substance/texture/blob/alpha-3-integration/examples/editor.html) 

@oliver----  @michael is there a better way to do this? I have installed texture and ran `npm run bundle` . Is there a master css / javascript file that include all stylesheets / scripts than I can include or I still have to declare all dependencies similar to `editor.html`?

Please advise. thanks.

**Comment by axfelix** [comment]
@kaschioudi per the above conversation, you should be able to copy the block in their release demo that does https://github.com/kaschioudi/ojs3-markup/issues/27#issuecomment-318806423 instead

**Comment by kaschioudi** [comment]
Have you guys seen https://github.com/kaschioudi/ojs3-markup/blob/master/texture/js/store.js and https://github.com/kaschioudi/ojs3-markup/blob/master/texture/js/app.js ?

I believe these are the XML store and the boot-script respectively.  

But my question was regarding the dependencies files to load in `editor.tpl`. I have been including all stylesheets and javascript files as per `editor.html` (from texture example directory). Is there a better way to do this? Does the bundle script generate a single stylesheet and script file which could be included directly instead of multiple includes?

**Comment by axfelix** [comment]
Oh, I wasn't sure that we could still use that method -- will need the substance guys to clarify.

**Comment by michael** [comment]
Hi @kaschioudi @axfelix !

editor.tpl looks good, this should work. You could run a JS bundler to have just one file, but I think it is also ok to have several files.

The bootscript changed a little bit, instead of specifying an XMLStore, you directly provide readXML and writeXML functions. You could still keep your XMLStore but change app.js like so:

```js
window.onload = function() {
  var xmlStore = new OJSXMLStore()
  var app = Texture.mount({
    documentId: document.querySelector('meta[name=jobId').getAttribute('content'),
    readXML: xmlStore.readXML,
    writeXML: xmlStore.writeXML
  }, document.body)
  window.app = app
}
```

Cheers, Michael

**Comment by axfelix** [comment]
Working! Thanks!

**Comment by kaschioudi** [comment]
thanks @michael for you reply. it was helpful.

However, I can't get saving to work properly. Not sure whether I'm doing something wrong or it's a bug in Texture. Basically the value for `documentId` from the context object is `undefined`. (see https://github.com/substance/texture/blob/b4ee8f123b97d5cbd04526d60a53cfa2f77e5978/src/editor/util/SaveHandler.js#L17)

Any idea what's happening? Thanks.

**Comment by michael** [comment]
@kaschioudi I published a patch release, where this issue should be fixed:

https://github.com/substance/texture/releases/tag/v1.0.0-alpha.3.1

Use the contents from the attached zip file.

**Comment by kaschioudi** [comment]
thanks @michael .
