### ISSUE TITLE
Make Convert to XML and Generate Galleys links appear only where appropriate

### ISSUE THREAD

**Issue by jalperin** [kaschioudi/ojs3-markup#34]
Convert links should only appear on doc, docx, and PDF. Definitely should not be appearing on the XML files (for example). 

Generate Galley files should only appear on XML? Or maybe its on the same file types.

**Comment by axfelix** [comment]
Convert link can go away for XML, yeah.

Generate galley should appear for all filetypes, though -- we support going directly from Word/PDF to the galleys if a user wants.

**Comment by axfelix** [comment]
And it looks like the Convert link for XML files wasn't there until recently... so that's a regression. @kaschioudi

**Comment by kaschioudi** [comment]
https://github.com/kaschioudi/ojs3-markup/commit/cfac0bdf428a53d6905140209940aaaf4f34a5f3 should fix this issue.
