### ISSUE TITLE
Journal title should be provided by OJS to OTS

### ISSUE THREAD

**Issue by asmecher** [kaschioudi/ojs3-markup#38]
In @kaschioudi's latest test, the journal title appears to be detected from the document by OTS, rather than supplied by OJS.

**Comment by axfelix** [comment]
I'm guessing that this and https://github.com/kaschioudi/ojs3-markup/issues/39 are because @kaschioudi's own branch of OTS that he tested against hasn't been updated since https://github.com/pkp/ots/pull/103

**Comment by axfelix** [comment]
Probably also https://github.com/kaschioudi/ojs3-markup/issues/41

**Comment by kaschioudi** [comment]
@asmecher : @axfelix is right. I am not running the latest code of OTS in my instance. I will update my OTS install and restart the conversion.

**Comment by asmecher** [comment]
Thanks, @kaschioudi -- see if you can run the test early next week, then if you can pass along the generated XML, I can send it to Erudit for comparison with the OJS 2.x NLM XML.

**Comment by kaschioudi** [comment]
@asmecher I have refreshed my OTS install with latest version of master branch and have noticed that conversions get stuck at some point in the pipeline. I have notified @axfelix and waiting for his feedback. I will keep you posted.
