### ISSUE TITLE
Submissions without abstracts in OJS get them detected by OTS

### ISSUE THREAD

**Issue by asmecher** [kaschioudi/ojs3-markup#40]
Some submissions won't have metadata in OJS (e.g. abstracts). The absence of an abstract is useful information, and I'd suggest when that's the case, it should prevent OTS from attempting to grab one from the document, as I expect it'll be a low-quality match for an important piece of metadata.

That should probably apply more broadly to metadata that OJS can provide -- thinking e.g. about journals that don't provide a full set of volume/number/year data.

(Open to ideas around this, @kaschioudi and @axfelix.)

**Comment by axfelix** [comment]
Would it be sufficient for OTS to not attempt to parse *any* missing metadata in cases where it receives any known-good metadata from OJS? In other words, should including metadata as an input parameter to OTS skip any other front matter parsing entirely?

**Comment by asmecher** [comment]
Yes, I think that would be a safe approach.

**Comment by axfelix** [comment]
OK, good, that's the current behaviour :)
