### ISSUE TITLE
Suggested for new tags support

### ISSUE THREAD

**Issue by Vitaliy-1** [kaschioudi/ojs3-markup#42]
Greetings,

These tags are not currently supported by Texture, but are supported by Lens Viewer plugin and JATS standards:
`article/front/journal-meta/journal-title-group/journal-title`
`article/front/article-meta/title-group/article-title`
`article/back/ref-list/ref/element-citation/ext-link`
It would be great to include them in the plugin.

**Comment by axfelix** [comment]
These should all be supported by Texture currently or planned to be.
