### ISSUE TITLE
"User ID" should presumably be email

### ISSUE THREAD

**Issue by asmecher** [kaschioudi/ojs3-markup#43]
In the settings form, we refer to "User ID". This language isn't used elsewhere -- the OTS website uses email addresses for logins. Make the language consistent.

**Comment by axfelix** [comment]
Good point -- done for en_US in https://github.com/kaschioudi/ojs3-markup/commit/fd0556c0018b60ae986bce9d06ff622683ebcda2

@kaschioudi, I'll let you review Alec's other recent issues. I don't think any are urgent but we should eventually be implementing all of them.
