### ISSUE TITLE
Exclude incomplete submissions from batch conversion list

### ISSUE THREAD

**Issue by asmecher** [kaschioudi/ojs3-markup#44]
Submissions with `submissions.submission_progress<>0` should not be listed in the batch conversion tool.

**Comment by kaschioudi** [comment]
@asmecher : this had already been fixed in this commit from last week: https://github.com/kaschioudi/ojs3-markup/commit/21a0f98d9e3745ae670f2a387744edcfff8428e8

(cf. https://github.com/kaschioudi/ojs3-markup/blob/45-fix/classes/MarkupBatchConversionHelper.inc.php#L132-L135)

**Comment by asmecher** [comment]
OK, thanks!
