### ISSUE TITLE
Consider batch conversion tools for large multi-journal installs

### ISSUE THREAD

**Issue by asmecher** [kaschioudi/ojs3-markup#45]
Currently the OTS plugin operates on a per-journal basis, e.g. for configuration, batch migration, etc.
Some installs may have a lot of journals, and configuring and running the plugin on a journal-by-journal basis may not be practical. Consider tools for facilitating large-scale conversion.

I would suggest a command-line tool for multi-journal installs.

(OTOH I think we already support overriding some settings via `config.inc.php` such as OTS credentials -- is that correct?)

**Comment by kaschioudi** [comment]
@asmecher 
https://github.com/kaschioudi/ojs3-markup/pull/53

**Comment by kaschioudi** [comment]
> (OTOH I think we already support overriding some settings via config.inc.php such as OTS credentials -- is that correct?)

No, OTS credentials are stored only in the database.

**Comment by asmecher** [comment]
I think it's worth adding the option for administrators of large collections to specify the OTS API credentials in `config.inc.php`, making it unnecessary to set them up for every journal. (@axfelix, I have a vague recollection of talking about this before?)

**Comment by axfelix** [comment]
I don't think we ever moved on that but I'd be all in favour of doing it here! Not sure what the usual template is for doing that in a plugin if there is one.

**Comment by kaschioudi** [comment]
@asmecher is it okay to have a plugin configuration in `config.inc.php` ? Or there is an existing pattern to follow? if so please point me. thanks.

**Comment by asmecher** [comment]
See e.g. https://github.com/pkp/ojs/blob/master/plugins/generic/backup/BackupPlugin.inc.php#L82

**Comment by kaschioudi** [comment]
https://github.com/kaschioudi/ojs3-markup/pull/53/commits/9e4f676b2563cb9cd30bf529d8bde744ed1d3bcd

**Comment by kaschioudi** [comment]
Below is the new config block to add to config.inc.php. @asmecher could you please create an issue for OJS so that I can make a PR? 
```
;;;;;;;;;;;;;;;;;;
; Markup plugin  ;
;;;;;;;;;;;;;;;;;;

[markup]

; OTS email address used for login
ots_login_email = ''

; Token for OTS api authentication. Get this token from your OTS settings page
ots_api_token = '' 

; Open Typesetting Stack instance to connect to. Normally you should not change this setting.
ots_host = 'http://pkp-xml-demo.lib.sfu.ca'
```

**Comment by asmecher** [comment]
Do you mean a PR for adding this block to the default OJS configuration file? I wouldn't suggest doing that -- plugin details should stay outside the core codebase, especially if they aren't distributed with OJS. Instead, I'd suggest documenting the plugin's configuration options in the plugin's README.

**Comment by kaschioudi** [comment]
Here (https://github.com/kaschioudi/ojs3-markup/issues/45#issuecomment-369672780) I was asking if it was okay to include plugin configs in `config.inc.php`. Which I found odd.

Alright, so the plugin checks `config.inc.php` for these configs but it's the end-user's who's in charge of adding the configs to `config.inc.php`. However we should update README to include that information. Correct?

**Comment by asmecher** [comment]
Yes, that's correct.

**Comment by kaschioudi** [comment]
@axfelix : since you've written most of the README, would you like to document how administrators could set credentials from `config.inc.php`?

**Comment by axfelix** [comment]
Yup, sure thing. Sorry for the confusion here, I couldn't tell what was being asked either.

**Comment by kaschioudi** [comment]
Here's how the admin could set default citation style to APA in config.inc.php

```
; Preferred citation style for PDF and ePub output
ots_citation_style_hash = '3f0f7fede090f24cc71b7281073996be'
```
Commit: https://github.com/kaschioudi/ojs3-markup/commit/b7444743a6eb17aff46ec8c3a3d15aa645c3bf4e

I have modify the settings form to also hide the CSL select list when a default is set in config file.

**Comment by asmecher** [comment]
@axfelix, are these hashes really the best way to specify a CSL to OTS? It seems brittle to me.

**Comment by axfelix** [comment]
It's been working fine for several years; I can't remember it if Michael originally came up with it or it's actually tied to the CSV repo we pull from but we have an API call to list them and everything.

**Comment by asmecher** [comment]
How stable are they?

**Comment by axfelix** [comment]
https://github.com/pkp/ots/blob/master/module/CitationstyleConversion/src/CitationstyleConversion/Model/Citationstyles.php#L50

Looks like the hash is derived from the file names themselves in https://github.com/citation-style-language/styles, so -- very.

**Comment by asmecher** [comment]
Hmm, it's a shame there's no proper listing or symbolic naming in the CSL repository. OK, if it's stable, it'll do.

**Comment by axfelix** [comment]
Implemented in https://github.com/kaschioudi/ojs3-markup/pull/53 !
