### ISSUE TITLE
Double-check protections against malicious invocation of the batch conversion gateway plugin

### ISSUE THREAD

**Issue by asmecher** [kaschioudi/ojs3-markup#46]
At a glance, there is no protection against malicious invocation of the batch conversion gateway plugin. Make sure it can't be abused.

**Comment by kaschioudi** [comment]
@asmecher : is there any pattern/practice in place for this use case somewhere else in OJS I should follow? 

if no, what do you think about create a temporary file containing a unique id whose hash is passed to the gateway (from `MarkupBatchConversionHandler::startConversion()`). On the gateway side (`MarkupBatchGatewayPlugin::fetch()`), once a request is received:

1. Look for the hash 
2. Locate the temporary file 
3. Validate the hash. 
4. Delete the temporary file

Let me know.

**Comment by asmecher** [comment]
@kaschioudi, the plugin should only be invoked by a user who is currently logged in as a journal manager, correct? You can use the `userHasRole` function in RoleDAO to check this. I don't think there's a risk of one journal manager trying to step on another journal manager's conversion -- journal managers are privileged roles and once you've got a journal manager account the system is largely open to you.

(I think this change needs to be made to both gateway plugins, at a glance.)

**Comment by kaschioudi** [comment]
> the plugin should only be invoked by a user who is currently logged in as a journal manager, correct? 

Yes. Well the batch conversion part. (other features like XML Conversion and Galley files generation are available to users with other roles. cf. https://github.com/kaschioudi/ojs3-markup/blob/45-fix/MarkupHandler.inc.php#L31-L35)

@asmecher : I just want to double check something. In this particular case the gateway plugin is invoked via CURL so `$request->getUser();` returns `null`. How do I get a valid $user object ? 

At the moment, userID is fetched from the URL and I look for the user object via userDAO. I could then try to valid access using `$roleDao->userHasRole($context->getId(), $user->getId(), ROLE_ID_MANAGER)`. But (correct me if I am wrong) that would mean anybody who knows a journal manager user ID could trigger this URL right?

**Comment by asmecher** [comment]
> In this particular case the gateway plugin is invoked via CURL so $request->getUser(); returns null

Of course, I forgot about that.

The trouble with just checking the user ID, as you say, is that unless I've missed something you could guess any manager's user ID and that would be enough.

I can think of two mechanisms that might work...
- The AccessKey mechanism; see `lib/pkp/classes/security/AccessKeyManager.inc.php`
- Store a random value in `user_settings` in the calling code, then check it in the gateway plugin using `PKPUserDAO::getBySetting`

I'd suggest looking into access keys as the first choice, since it's an already-existing mechanism -- but I haven't used it for quite a while, so there may be potential mismatched requirements.

**Comment by kaschioudi** [comment]
@asmecher see https://github.com/kaschioudi/ojs3-markup/commit/163689ee44e631cebe71b1d15ccfe19279f99c41
