### ISSUE TITLE
Maintain compatibility with ojs master (for 3.1.1 release)

### ISSUE THREAD

**Issue by asmecher** [kaschioudi/ojs3-markup#50]
Currently the master branch of ojs3-markup is not compatible with the OJS3 master branch.

I'd suggest creating a new `ojs-stable-3_1_0` branch, then maintaining OJS 3.1.x compatibility there. The forthcoming PR should then be merged into the master branch.

**Comment by asmecher** [comment]
PR: https://github.com/kaschioudi/ojs3-markup/pull/51

**Comment by asmecher** [comment]
@kaschioudi, it doesn't look like the `ojs-stable-3_1_0` branch got created before merging this.

**Comment by kaschioudi** [comment]
@asmecher : I just pushed the branch.
