### ISSUE TITLE
Untranslated locale key "submission.copyrightStatement" appears in OTS XML

### ISSUE THREAD

**Issue by asmecher** [kaschioudi/ojs3-markup#52]
The untranslated key `submission.copyrightStatement` appears in OTS XML. It appears to be injected by the OTS plugin. The respective locale file needs to be loaded before the key is used.

**Comment by kaschioudi** [comment]
@asmecher : not sure how plugins manually load their locale file. I know of `AppLocale::requireComponents` which take `LOCALE_COMPONENT_...` constants

is it `$this->addLocaleData();` in plugin's `register()` ?

**Comment by asmecher** [comment]
That locale key is in the `pkp-lib` locale files, not the plugin locale files, so you'd need to load the right locale file with

    AppLocale::requireComponents(LOCALE_COMPONENT_PKP_SUBMISSION);

**Comment by kaschioudi** [comment]
My bad. I understood the local key was coming from the plugin.

**Comment by asmecher** [comment]
@kaschioudi, I ran into this again today -- don't forget to make sure everything in `ojs-stable-3_1_0` also gets forward-ported to `master`!

**Comment by kaschioudi** [comment]
@asmecher : @axfelix and I have been waiting for you OK to merge `ojs-stable-3_1_0` into `master`. Let me know if I can go ahead with the merge.

**Comment by asmecher** [comment]
Is there a pull request open for this? I didn't know you were waiting for me.
