### ISSUE TITLE
Convert to XML, Trigger Job, Batch Conversion not working (?)

### ISSUE THREAD

**Issue by coastalplain** [kaschioudi/ojs3-markup#55]
We have been working with the OTS Markup plugin using Journal-wide Authentication and the demo OTS site.  On the [OTS Site](http://pkp-xml-demo.lib.sfu.ca) we can convert a word docx (Thanks, @axfelix!).  When that same docx is loaded on to an OJS site and we try to create an XML using the OTS service, we are not getting a result.  From an individual submission, we click the "Convert to XML" and get the window "Confirm submission of OTS job" and "trigger job" button, but nothing seems to happen.

From the OTS Backlog conversion (Website Settings -> OTS Backlog conversion), we can select a file to convert:
![image](https://user-images.githubusercontent.com/8905768/40091210-60e6fd44-5884-11e8-8430-4561e8cddabb.png)

...and "Start Conversion"
![image](https://user-images.githubusercontent.com/8905768/40091219-6f0a34d6-5884-11e8-83d8-b11e170e29d5.png)

which brings up the "Batch conversion job infos"[sic] window:
![image](https://user-images.githubusercontent.com/8905768/40091328-f9e9f26c-5884-11e8-9acd-f33b7ff2a195.png)

That never disappears.

Is there a log or other place to check or provide information?  On the [demo site](http://pkp-xml-demo.lib.sfu.ca) I don't see an entry or that anything happened under that API Token and email address.  Very happy to assist where possible.

**Comment by axfelix** [comment]
First question -- are you using the master branch, or ojs-stable-3_1_0? the latter is actually much newer (we meant to merge this after the last batch of work and only realized today that didn't happen). That's an oversight on our part and I bet it'll fix the issues you're having...

**Comment by coastalplain** [comment]
Yes (I downloaded and reinstalled just in case).

**Comment by kaschioudi** [comment]
hi @coastalplain ,

Under the hood, there's a temporary file used for inter-process communication which gets created at the beginning of a batch conversion and deleted thereafter (unless there was a fatal error during the batch conversion). Check if that file exists in you system. The file name is `markupBatch.out` and is located in your system temporary directory (`/tmp` by default). Let me know if it does not work.

**Comment by coastalplain** [comment]
Hi, @kaschioudi 
I found the file and it appears to have the correct time for the most recent attempt (I verified several times).  In this particular test, I tried to select three files from different submissions.  The markupBatch.out contains the following single row of text:
>a:3:{s:3:"pid";i:8585;s:15:"submissionCount";i:3;s:14:"processedCount";i:0;}

I can "Cancel" the operation, although it says "cannot cancel" and when I run a single file (that I know works on the demo site), the file again contains one line:

>a:3:{s:3:"pid";i:27727;s:15:"submissionCount";i:1;s:14:"processedCount";i:0;}

Thank you for the assistance--if you need any other testing, please ask.

**Comment by kaschioudi** [comment]
@coastalplain , I suspect you are running into a PHP fatal error, which is stopping the execution. Please monitor your PHP error logs and let me know if you see any entry during the conversion.

**Comment by coastalplain** [comment]
@kaschioudi , I get a DB Error:

>[16-May-2018 21:24:02 America/New_York] ojs2: DB Error: Table 'username_eaj302.markup_jobinfos' doesn't exist

And that is correct.  I checked mySQL and it is not in there.  I did run `php tools/upgrade.php upgrade` and `php tools/dbXMLtoSQL.php -schema execute`  after installing the markup plugin under generic.   Is there a manual table creation script?

**Comment by kaschioudi** [comment]
humm running those command should have created the `markup_jobinfos` table. @asmecher can you think of a reason why `markup_jobinfos` does not get created?

**Comment by coastalplain** [comment]
@kaschioudi and @asmecher 
The table was not created due to a PHP version error.   Being on a shared server, PHP7 is the default, and the command to upgrade the database needs less than PHP7. To find the various flavors available (to those who do not know):
`whereis php`
I found the highest version below 7, in my case php56 and ran that php version against the scripts
`/opt/imh/imh-php56/root/usr/bin/php tools/upgrade.php upgrade`
That inserted the correct table into the DB for markup.  Running fine now except I can't find the xml...I think that is another issue.

Apologies for the tail chasing, but thank you very much for your direction!
