### ISSUE TITLE
Revisit "save" behaviour in Substance

### ISSUE THREAD

**Issue by axfelix** [kaschioudi/ojs3-markup#7]
Right now, changes made in Substance are not persisted when dismissing a browser window, unlike Google docs; it's necessary to click the Save button in the interface.

Clicking the save button _does not_ register a new version of the document in OJS, unlike the typical OJS behaviour, where all revisions are retained separately.

Ideally, we'd want to change both of these things to provide familiar UX -- 1) add automatic, incremental saving in Substance, and 2) make the Save button trigger a new OJS draft revision. However, they need to both be implemented at the same time, and 1) is not trivial to implement in Substance, so it may need to wait for a future development round.

**Comment by axfelix** [comment]
@kaschioudi more pressing issue -- save behaviour in Substance appears to be broken in the current build; we need to define an XML store for it to use: https://github.com/substance/texture/issues/124#issuecomment-279066801

**Comment by axfelix** [comment]
Planned behaviour is as follows:

- Clicking the save button in Texture will a) register a new draft of the document in OJS (as though a new Word or PDF draft had been uploaded), b) save the current Texture changes to this new draft, and c) post back any front matter changes to OJS article metadata (through DB calls or helper functions).

- Editing metadata for any article directly in OJS will also make changes to the *newest* version of all XML documents registered as article text in all workflow stages. These code paths still have to be rewritten but should be relatively straightforward; all metadata that this plugin normally touches is effectively documented in https://github.com/kaschioudi/ojs3-markup/blob/master/MarkupGatewayPlugin.inc.php#L327.

- Texture autosaving of changes (Google Docs style) can be toggled on and off in plugin settings; will always update the current file in OJS. Should this automatically register a new draft  per-session whenever it's enabled and a draft is edited? Trying to figure out what's most intuitive. @asmecher ?

**Comment by asmecher** [comment]
> Texture autosaving of changes (Google Docs style) can be toggled on and off in plugin settings; will always update the current file in OJS. Should this automatically register a new draft per-session whenever it's enabled and a draft is edited? Trying to figure out what's most intuitive.

In OJS's current file model, the most recent revision is *always* the "current" version, i.e. there is no way to post a "draft" without having it operative. I would suggest a "save button" approach; when clicked, it'll post the current file to OJS as a new revision.

**Comment by axfelix** [comment]
We could do that *and* the auto save though, given that the backend already supports it; in my mind this is a vote in favour of "every session automatically generates a new draft and auto saves to that"

**Comment by asmecher** [comment]
Would the drafts be saved in OJS? Where?

**Comment by axfelix** [comment]
Yes -- the idea is that every new Texture session that performs any autosaving of changes would automatically register a new draft with OJS, and the save button would manually register yet another, like a "Save As".

**Comment by asmecher** [comment]
But as above:
> In OJS's current file model, the most recent revision is always the "current" version, i.e. there is no way to post a "draft" without having it operative.

**Comment by axfelix** [comment]
Oh, crud. OK, I wasn't fully grasping that limitation. I guess we can just disable the autosave behaviour outright for the time being, then. Is there a chance that we'd be able to work around this in the future?

**Comment by asmecher** [comment]
I don't have any plans to change it, though I'm open to proposals. Longer term, we've discussed replacements for the current file model, i.e. one of the various git implementations or similar, but haven't come to a concrete decision.

**Comment by axfelix** [comment]
https://github.com/substance/texture/blob/master/examples/editor.js#L81

Manual save example for newest Texture so I don't forget

**Comment by axfelix** [comment]
@kaschioudi, Texture is nearing another release that a) properly stabilizes manual saving as a function that can be called separately by a wrapper (see link in previous comment) and b) provides a proper filesystem backend for image uploads. I just made a few changes to OTS to make sure the JATS we're producing should no longer create issues for Texture's strict subset, and we're going to want to implement saving and image uploads properly in OJS (i.e. by making Texture use the OJS `files` directory directly) so we can drop in the upgraded Texture release after I finish testing the RC.

**Comment by axfelix** [comment]
@kaschioudi , have you had time to start looking into this + Texture 4 integration yet?

**Comment by kaschioudi** [comment]
> b) provides a proper filesystem backend for image uploads.

@axfelix : where could I get documentation about this ?

**Comment by axfelix** [comment]
I only have an example for the Save behaviour, not the image backend:

https://github.com/substance/texture/issues/330

**Comment by kaschioudi** [comment]
Here's the PR:

https://github.com/kaschioudi/ojs3-markup/pull/58
