### ISSUE TITLE
Make the "generate galleys for publication" interaction more distinct from the "convert to XML [for editing]" interaction

### ISSUE THREAD

**Issue by axfelix** [kaschioudi/ojs3-markup#8]
Right now, the original plugin interaction of submitting a job to the stack only at publication time to populate XML/PDF/ePub galleys has not been looked at for a while, and needs to be better separated from conversion for editing purposes.

**Comment by axfelix** [comment]
Fixed, but leaving this open pending future UX feedback.

**Comment by kaschioudi** [comment]
@axfelix : I was unable to reproduce the issue you reported on Feb 17th regarding galey files generation. I tried with the latest version of the plugin and it's working fine. Could you please provide more information or send me a zip of your plugin folder so that I can try to reproduce the issue. Thanks.

**Comment by axfelix** [comment]
I'm on vacation this wk but left @jmacgreg information to kick off the external testing pending this issue while I'm gone -- if he also can't reproduce then I won't worry about it.

**Comment by axfelix** [comment]
OK, back from vacation -- @kaschioudi, can you log in to http://lib-garnett.lib.sfu.ca/ojs-plugin-alpha-1 with the credentials I'm sending via Slack right now, and tell me if I'm not seeing the galley generation link under the production tab of the active submission because of a mistake I made, or if I've actually triggered a bug?

**Comment by kaschioudi** [comment]
welcome back @axfelix. galley generation link appears for doc, docx and pdf. Should we include xml files as well?

**Comment by axfelix** [comment]
Aha! That was it, then. Yeah, let's add XML too. Sorry for the confusion.

**Comment by axfelix** [comment]
Working, closing :)
