### ISSUE TITLE
There's a fifth, "internal review" stage listed in plugin config, missing locale keys

### ISSUE THREAD

**Issue by axfelix** [kaschioudi/ojs3-markup#9]
On the plugin config page, there's a fifth stage listed in addition to the usual Submission/Review/etc, and it currently comes through as:

` ##workflow.review.internalReview##`

I'm assuming this is anticipating an upstream change where such a stage will be added to OJS 3.1, but it probably should be hidden for versions where that locale key is missing.

**Comment by kaschioudi** [comment]
These are all the stages in OJS core. That specific stage refers to "Internal Review" and from I was told that it's used by OMP. The label is not displaying probably because I am not loading some locale file. I will look into it.

**Comment by axfelix** [comment]
This is still outstanding in 3.0.1, haven't tested in 3.0.2.

**Comment by axfelix** [comment]
This is fixed using the last working commit of this plugin in 3.0.2 and can be closed.
